-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/user_mentions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE /*_*/user_mentions (
  um_user INT UNSIGNED NOT NULL,
  um_rev INT UNSIGNED NOT NULL,
  um_author INT UNSIGNED NOT NULL,
  um_page INT UNSIGNED NOT NULL,
  PRIMARY KEY(um_user, um_rev)
) /*$wgDBTableOptions*/;
