-- This file is automatically generated using maintenance/generateSchemaSql.php.
-- Source: db/user_mentions.json
-- Do not modify this file directly.
-- See https://www.mediawiki.org/wiki/Manual:Schema_changes
CREATE TABLE user_mentions (
  um_user INT NOT NULL,
  um_rev INT NOT NULL,
  um_author INT NOT NULL,
  um_page INT NOT NULL,
  PRIMARY KEY(um_user, um_rev)
);
